# Generated by Django 3.0.5 on 2020-05-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0119_remove_producttype_beidl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributecustom', to='product.Attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributecustom', to='product.ProductType')),
            ],
            options={
                'ordering': ('sort_order',),
                'unique_together': {('attribute', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='product_custom_types',
            field=models.ManyToManyField(blank=True, related_name='custom_attributes', through='product.AttributeCustom', to='product.ProductType'),
        ),
    ]
