# Generated by Django 3.0.5 on 2020-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0120_auto_20200513_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='is_customizable',
            field=models.BooleanField(default=False),
        ),
    ]
