# Generated by Django 3.0.5 on 2020-05-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0121_producttype_is_customizable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeCustom',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='product_custom_types',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='is_customizable',
        ),
    ]
