version: '3.8'

services:
  api:
    ports:
      - 8010:8000
    container_name: live-saleor-local
    image: saleor-api:live
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: 'https://valcometv-media.s3.eu-central-1.amazonaws.com/statics/valcometv/'
    restart: unless-stopped
    volumes:
      - live-local-media
    networks:
      - live-local-backend
    env_file:
      - local.env
      - secret.env
    user: saleor


  dashboard:
    image: saleor-dashboard:live
    build:
      context: ../../saleor-dashboard
      dockerfile: ./Dockerfile.Dev
      args:
        API_URI: 'http://localhost:8010/graphql/'
    container_name: live-saleor-dashboard-local
    networks:
      - live-local-backend
    ports:
      - 9010:9000
    restart: unless-stopped
    volumes:
      - /app/node_modules/
    command: npm start -- --host 0.0.0.0
    healthcheck:
      test: [ "CMD", "curl", "-f", "-o", "/dev/null", "-I", "-w", "\"%{http_code}\"", "http://localhost:9000" ]
      retries: 30
      interval: 5s
      start_period: 30s

  worker:
    image: saleor-worker:live
    build:
      context: ../
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: 'https://valcometv-media.s3.eu-central-1.amazonaws.com/statics/valcometv/'
    container_name: live-worker-local
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info
    restart: unless-stopped
    volumes:
      - live-local-media
    networks:
      - live-local-backend
    env_file:
      - local.env
      - secret.env
    user: saleor


volumes:
  live-local-media:
    driver: local

networks:
  live-local-backend:
    external: true
