# Generated by Django 3.1.8 on 2021-05-12 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SINGLE', 'single'), ('DAY', 'day'), ('TEAM', 'team'), ('LEAGUE', 'league')], max_length=256)),
                ('version', models.IntegerField(default=1)),
                ('game_id', models.CharField(blank=True, max_length=256, null=True)),
                ('team_id', models.CharField(blank=True, max_length=256, null=True)),
                ('season_id', models.CharField(blank=True, max_length=256, null=True)),
                ('expires', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('expires',),
            },
        ),
    ]
