# Generated by Django 3.1.8 on 2021-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamticket',
            old_name='team_id',
            new_name='team_ids',
        ),
        migrations.AddField(
            model_name='streamticket',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamticket',
            name='league_ids',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='streamticket',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='streamticket',
            name='timed_type',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AlterField(
            model_name='streamticket',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'single'), ('TIMED', 'timed'), ('SEASON', 'season')], max_length=256),
        ),
    ]
