# Generated by Django 3.1.8 on 2021-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20210609_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamticket',
            name='access_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
