# Generated by Django 3.2.3 on 2021-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_auto_20210824_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamticket',
            name='for_guests',
            field=models.BooleanField(default=False),
        ),
    ]
