# Generated by Django 3.2.3 on 2021-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_streamticket_for_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamticket',
            name='stream_type',
            field=models.CharField(default='Game', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamticket',
            name='video_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
