# Generated by Django 3.2.12 on 2022-11-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0116_auto_20211207_0705'),
        ('streaming', '0005_auto_20211004_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamticket',
            old_name='is_free',
            new_name='hide_in_analytics',
        ),
        migrations.AddField(
            model_name='streamticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order.order'),
        ),
        migrations.AddField(
            model_name='streamticket',
            name='product_slug',
            field=models.CharField(choices=[('single', 'single'), ('cup', 'cup'), ('season', 'season'), ('playoff-season', 'playoff-season'), ('regular-season', 'regular-season')], default=None, max_length=256, null=True),
        ),
    ]
