# Generated by Django 3.2.12 on 2023-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_auto_20221110_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamticket',
            name='product_slug',
            field=models.CharField(choices=[('single', 'single'), ('cup', 'cup'), ('season', 'season'), ('playoffs', 'playoffs'), ('regular-season', 'regular-season')], default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='streamticket',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'single'), ('TIMED', 'timed'), ('SEASON', 'season'), ('TIMED_SEASON', 'timed_season')], max_length=256),
        ),
    ]
