# Generated by Django 3.2.12 on 2023-07-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_auto_20230320_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamticket',
            name='team_restriction',
            field=models.CharField(choices=[('allow-both', 'allow-both'), ('home-only', 'home-only'), ('guest-only', 'guest-only')], default='home-only', max_length=256),
        ),
        migrations.RunSQL("""
        UPDATE streaming_streamticket
        SET team_restriction = 'allow-both'
        WHERE (team_ids is null OR for_guests = true) AND type = 'season'
        """)
    ]
