# Generated by Django 3.2.12 on 2023-07-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_streamticket_team_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamticket',
            name='access_state',
            field=models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('fully-refunded', 'fully-refunded'), ('partially-refunded', 'partially-refunded')], default='active', max_length=256),
        ),
    ]
