# Generated by Django 3.2.12 on 2023-08-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_streamticket_access_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamticket',
            name='for_guests',
        ),
    ]
