# Generated by Django 3.0.6 on 2020-09-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_payment_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent',
        ),
    ]
