# Generated by Django 3.0.6 on 2020-09-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_remove_payment_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
