# Generated by Django 3.0.6 on 2020-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_payment_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_intent',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
