# Generated by Django 3.2.3 on 2021-06-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_drop_searchable_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent',
        ),
    ]
