# Generated by Django 3.2.12 on 2022-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_payment_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='psp_refund_amount',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='psp_state',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='psp_reference',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True),
        ),
    ]
