# Generated by Django 3.2.12 on 2022-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_auto_20221019_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='psp_refund_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='psp_state',
            field=models.CharField(choices=[('not-charged', 'Not charged'), ('pending', 'Pending'), ('partially-charged', 'Partially charged'), ('fully-charged', 'Fully charged'), ('partially-refunded', 'Partially refunded'), ('fully-refunded', 'Fully refunded'), ('refused', 'Refused'), ('cancelled', 'Cancelled')], default=None, max_length=20, null=True),
        ),
    ]
