# Generated by Django 3.0.6 on 2021-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0025_auto_20200221_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='webhook_processing',
            field=models.BooleanField(default=False),
        ),
    ]
