# Generated by Django 3.0.6 on 2020-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20200427_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gender',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
