# Generated by Django 3.0.6 on 2020-07-30 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200728_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamticket',
            name='expires',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='streamticket',
            name='league_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='streamticket',
            name='stream_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='streamticket',
            name='team_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='streamticket',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'single'), ('DAY', 'day'), ('TEAM', 'team'), ('LEAGUE', 'league')], max_length=256),
        ),
    ]
