# Generated by Django 3.0.6 on 2020-09-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20200730_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamticket',
            old_name='stream_id',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='streamticket',
            old_name='league_id',
            new_name='season_id',
        ),
    ]
