# Generated by Django 3.1.8 on 2021-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20210506_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gender',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
