# Generated by Django 3.2.3 on 2021-06-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20210506_1058'),
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_jwt_iat',
        ),
        migrations.RunSQL("""
            insert into streaming_streamticket (id, game_id, team_id, season_id, user_id, "type", expires, "version")
            select id, game_id, team_id, season_id, user_id, "type", expires, "version" from account_streamticket
        """
        ),
        migrations.DeleteModel(
            name='StreamTicket',
        ),
    ]
