# Generated by Django 3.0.6 on 2021-01-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_user_last_jwt_iat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
