# Generated by Django 3.0.6 on 2021-04-29 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_user_favorite_team'),
    ]

    operations = [

        migrations.AddField(
            model_name='streamticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamticket',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
