# Generated by Django 3.0.6 on 2021-04-29 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_streamticket_user'),
    ]

    operations = [

        migrations.RunSQL("""
            update account_streamticket
            set user_id = AUST.user_id
            from (
                select user_id, streamticket_id
                from account_user_stream_tickets
            ) as AUST
            where id = AUST.streamticket_id
        """
        ),
        migrations.RemoveField(
            model_name='user',
            name='stream_tickets',
        ),
    ]
